### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by OlliePugh** [ionkorol/korol-joystick#11]
I have raised a PR to fix this library not working on web over a month ago. No interactions with the PR. I'm wondering if this is abandoned?

**Comment by dannystaple** [comment]
I sure hope not - I've only recently discovered this.

**Comment by ionkorol** [comment]
It was for a bit but now it's not. @OlliePugh I will take a look at your pr and confirm the issue and the fix.

**Comment by ionkorol** [comment]
@OlliePugh I confirmed that there is an issue with the y axis being inverted. If you can clean up the pr I can work on merging it. For some reason I can't run the package on web, something around how the typescript is being built. `You may need an additional loader to handle the result of these loaders.`. This is the error that I am getting. Let me know if you guys have an idea on what the issue is.

**Comment by OlliePugh** [comment]
Okay, I can take a look, it was working fine for me. What steps are you doing to reproduce? just a create-expo-app?

**Comment by ionkorol** [comment]
Yes. the example folder has one setup.

**Comment by OlliePugh** [comment]
On my machine, main wont install through `yarn install`. And this error from building to web doesn't seem to come from my changes. I have not modified the build process.

**Comment by OlliePugh** [comment]
Any update on this? Still no response?

**Comment by OlliePugh** [comment]
Guess I will be cloning this and running my own fork 😓
